export const DEFAULT_DOMAINS = [
  "Distributed Systems",
  "React",
  "Architecture",
  "Backend",
  "Security",
  "DevOps",
  "Databases",
  "Machine Learning",
  "Web Performance",
  "Cryptography",
  "Consensus",
  "Performance",
  "Business Strategy",
  "Psychology",
  "Economics",
  "Management",
  "Marketing",
  "Writing",
];
